---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/tunupublsh/repositories/tunu-library
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && pip install --omit=dev